import { v4 as uuid } from 'uuid';
import Img1 from '../../assets/product-img.webp';

export const products = [
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Men premium trendy Jacket',
    originalPrice: '2000',
    discountedPrice: '1500',
    src: { url: Img1, alt: "Men's jacket" },
    gender: 'men',
    cod: true,
    fastDelivery: true,
    rating: 1,
    category: 'formals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Sobo',
    name: 'Men premium sports TShirt',
    originalPrice: '1500',
    discountedPrice: '1000',
    src: { url: Img1, alt: "Men's Tshirt" },
    gender: 'men',
    cod: false,
    fastDelivery: true,
    rating: 5,
    category: 'casuals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Men winter cool shoes',
    originalPrice: '3000',
    discountedPrice: '2500',
    src: { url: Img1, alt: 'sports shoes' },
    gender: 'men',
    cod: true,
    fastDelivery: false,
    rating: 3,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Women premium Tshirt',
    originalPrice: '3000',
    discountedPrice: '2800',
    src: { url: Img1, alt: 'Silk saree' },
    gender: 'women',
    cod: true,
    fastDelivery: false,
    rating: 4,
    category: 'casuals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Roadster',
    name: 'Men stylish casual shoes',
    originalPrice: '1000',
    discountedPrice: '700',
    src: { url: Img1, alt: 'Casual shoes' },
    gender: 'men',
    cod: true,
    fastDelivery: false,
    rating: 5,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Women premium stylish shoes',
    originalPrice: '2000',
    discountedPrice: '1500',
    src: { url: Img1, alt: 'Formal shoes' },
    gender: 'women',
    cod: true,
    fastDelivery: false,
    rating: 4,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Superdry',
    name: 'Men formal quality Jacket',
    originalPrice: '4000',
    discountedPrice: '3500',
    src: { url: Img1, alt: 'Formal jacket' },
    gender: 'men',
    cod: false,
    fastDelivery: true,
    rating: 2,
    category: 'formals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Men sports durable shoes',
    originalPrice: '1000',
    discountedPrice: '500',
    src: { url: Img1, alt: 'Climbing shoes' },
    gender: 'men',
    cod: false,
    fastDelivery: true,
    rating: 3,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Fashion',
    name: 'Women premium party shoes',
    originalPrice: '1000',
    discountedPrice: '500',
    src: { url: Img1, alt: 'Women party shoes' },
    gender: 'women',
    cod: true,
    fastDelivery: true,
    rating: 4,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Bewakoof',
    name: 'Men formal premium pants',
    originalPrice: '3000',
    discountedPrice: '2500',
    src: { url: Img1, alt: 'Formal pants' },
    gender: 'men',
    cod: false,
    fastDelivery: false,
    rating: 5,
    category: 'formals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: ' women casual party Jacket',
    originalPrice: '3000',
    discountedPrice: '2000',
    src: { url: Img1, alt: 'Women jacket' },
    gender: 'women',
    cod: false,
    rating: 2,
    category: 'partywear',
    fastDelivery: true,
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Sobo',
    name: 'Men round neck Tshirt',
    originalPrice: '700',
    discountedPrice: '500',
    src: { url: Img1, alt: 'Round Tshirt' },
    gender: 'women',
    cod: false,
    fastDelivery: false,
    rating: 1,
    category: 'casuals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Roadster',
    name: 'Men stylish casual shoes',
    originalPrice: '1000',
    discountedPrice: '700',
    src: { url: Img1, alt: 'Casual shoes' },
    gender: 'men',
    cod: true,
    fastDelivery: false,
    rating: 5,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Women premium stylish shoes',
    originalPrice: '2000',
    discountedPrice: '1500',
    src: { url: Img1, alt: 'Formal shoes' },
    gender: 'women',
    cod: true,
    fastDelivery: false,
    rating: 4,
    category: 'shoes',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Superdry',
    name: 'Men formal quality Jacket',
    originalPrice: '4000',
    discountedPrice: '3500',
    src: { url: Img1, alt: 'Formal jacket' },
    gender: 'men',
    cod: false,
    fastDelivery: true,
    rating: 2,
    category: 'formals',
    quantity: 1
  },
  {
    _id: uuid(),
    brand: 'Nike',
    name: 'Men sports durable shoes',
    originalPrice: '1000',
    discountedPrice: '500',
    src: { url: Img1, alt: 'Climbing shoes' },
    gender: 'men',
    cod: false,
    fastDelivery: true,
    rating: 3,
    category: 'shoes',
    quantity: 1
  }
];
